export const pets = [
  {
    id: 1,
    name: "Bella",
    breed: "Golden Retriever",
    age: "2 years",
    size: "Large",
    location: "Main Shelter",
    description: "Bella is a friendly and energetic golden retriever who loves playing fetch and swimming.",
    price: "$250",
    personality: ["Friendly", "Active", "Good with kids"],
    image: "https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=800&q=80", // Golden Retriever
  },
  {
    id: 2,
    name: "Whiskers",
    breed: "Persian Cat",
    age: "1 year",
    size: "Small",
    location: "City Shelter",
    description: "Whiskers is fluffy and calm, loves lounging in sunny spots.",
    price: "$180",
    personality: ["Calm", "Affectionate", "Gentle"],
    image: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?auto=format&fit=crop&w=800&q=80", // Persian Cat
  },
  {
      id: 3,
  name: "Luna",
  breed: "Labrador Retriever",
  age: "1 year",
  size: "Medium",
  location: "Happy Paws Shelter",
  description: "Luna loves cuddles and playing with toys.",
  price: "$300",
  personality: ["Playful", "Affectionate", "Gentle"],
  image: "https://images.unsplash.com/photo-1611254965886-e7caa829b627?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fExhYnJhZG9yJTIwUmV0cmlldmVyfGVufDB8fDB8fHww", // Labrador Retriever
},
  {
    id: 4,
    name: "Thumper",
    breed: "Rabbit",
    age: "8 months",
    size: "Small",
    location: "Downtown Shelter",
    description: "Thumper is curious and loves to nibble on veggies.",
    price: "$90",
    personality: ["Curious", "Gentle", "Quiet"],
    image: "https://images.unsplash.com/photo-1535241749838-299277b6305f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8UmFiYml0fGVufDB8fDB8fHww0", // Rabbit
  },
  {
    id: 5,
    name: "Polly",
    breed: "Parrot (Macaw)",
    age: "4 years",
    size: "Medium",
    location: "Main Shelter",
    description: "Polly is talkative, colorful, and loves attention.",
    price: "$220",
    personality: ["Talkative", "Playful", "Social"],
    image: "https://images.unsplash.com/photo-1645760314578-9a2db877a8b5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fFBhcnJvdCUyMChNYWNhdyl8ZW58MHx8MHx8fDA%3D", // Macaw Parrot
  },
  {
    id: 6,
    name: "Rocky",
    breed: "Bulldog",
    age: "5 years",
    size: "Medium",
    location: "City Shelter",
    description: "Rocky is calm, loves naps, and is great with kids.",
    price: "$260",
    personality: ["Calm", "Loyal", "Gentle"],
    image: "https://plus.unsplash.com/premium_photo-1723672818852-ba21ebdca79a?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGJ1bGxkb2d8ZW58MHx8MHx8fDA%3D", // Bulldog
  },
  {
    id: 7,
    name: "Milo",
    breed: "Husky",
    age: "3 years",
    size: "Large",
    location: "Happy Paws Shelter",
    description: "Milo is energetic, vocal, and loves the snow.",
    price: "$340",
    personality: ["Energetic", "Friendly", "Playful"],
    image: "https://plus.unsplash.com/premium_photo-1666229410352-c4686b71cea2?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGh1c2t5JTIwNGt8ZW58MHx8MHx8fDA%3D", // Husky
  },
  {
    id: 8,
    name: "Snowball",
    breed: "Angora Rabbit",
    age: "1.5 years",
    size: "Small",
    location: "Downtown Shelter",
    description: "Snowball is soft, fluffy, and enjoys gentle cuddles.",
    price: "$85",
    personality: ["Calm", "Gentle", "Quiet"],
    image: "https://images.unsplash.com/photo-1709104150242-fc3355663260?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fEFuZ29yYSUyMFJhYmJpdHxlbnwwfHwwfHx8MA%3D%3D", // Angora Rabbit
  },
  {
    id: 9,
    name: "Buddy",
    breed: "Rottweiler",
    age: "4 years",
    size: "Large",
    location: "Main Shelter",
    description: "Buddy is strong, protective, and loyal.",
    price: "$400",
    personality: ["Protective", "Loyal", "Gentle with family"],
    image: "https://images.unsplash.com/photo-1673474025690-eacc81e21daa?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Um90dHdlaWxlcnxlbnwwfHwwfHx8MA%3D%3D", // Rottweiler
  },
  {
    id: 10,
    name: "Coco",
    breed: "Cockatoo",
    age: "6 years",
    size: "Medium",
    location: "City Shelter",
    description: "Coco loves to sing and mimic sounds, very social.",
    price: "$200",
    personality: ["Social", "Loud", "Playful"],
    image: "https://images.unsplash.com/photo-1594524952992-0cddcede63dd?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Q29ja2F0b298ZW58MHx8MHx8fDA%3D", // Cockatoo
  },
];
